# D07 NumPy 的矩陣函式與線性代數應用

## 作業目標 

活用矩陣運算，實做線性代數 

## 作業重點

線性代數公式應用

矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

## 題目:

array1 = np.array([[10, 8], [3, 5]]) 

1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [2]:
import numpy as np

### 1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?

In [7]:
array1 = np.array([[10, 8], [3, 5]])

#計算反矩陣
array1_rev = np.linalg.inv(array1)
print('反矩陣 = \n', array1_rev)

#將反矩陣乘上原矩陣，並觀察是否為單位矩陣?
print('將反矩陣乘上原矩陣：\n', 
      np.dot(array1, array1_rev))

反矩陣 = 
 [[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
將反矩陣乘上原矩陣：
 [[1. 0.]
 [0. 1.]]


In [9]:
#2. 運用上列array計算特徵值、特徵向量?
val, vec = np.linalg.eig(array1)
print('矩陣 array1 = \n',array1,
      '\n特徵值 val = \n', val,   # eigenvalues
      '\n特徵向量 vec = \n', vec  # eigenvectors
     )


矩陣 array1 = 
 [[10  8]
 [ 3  5]] 
特徵值 val = 
 [13.  2.] 
特徵向量 vec = 
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [14]:
#3. 運用上列array計算SVD?
s, v, d = np.linalg.svd(array1)
print('s = ', s,
     '\nv = ', v,
    '\nd = ', d,
     )

s =  [[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]] 
v =  [13.94721714  1.86417116] 
d =  [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
