# 1. 矩陣乘積
## 1.1 點積 (dot product)：numpy.dot(a, b)

In [1]:
import numpy as np

In [8]:
a = np.arange(6).reshape(2, 3)
b = np.arange(12).reshape(3, 4)
print('a = \n', a,
      '\nb = \n', b)

In [13]:
#點積
#兩個多維陣列 (矩陣) 的點積，則中間兩個大小要相同才能進行點積

print('點積：\n', 'np.dot(a, b)=\n', np.dot(a, b))


點積：
 np.dot(a, b)=
 [[20 23 26 29]
 [56 68 80 92]]


## 1.2 內積：numpy.inner()

In [19]:
c = np.arange(5).reshape(1, 5)
d = np.random.randint(9, size=(5))
print('c = ', c,
      '\nd =', d)

c =  [[0 1 2 3 4]] 
d = [3 6 6 7 8]


In [20]:
#內積
#一般來說內積是2個一維陣列(向量)做內積
np.inner(c, d)

array([71])

## 1.3 外積：numpy.outer()

In [30]:
#外積
#外積是 2 個一維陣列(向量)做計算，若非一維陣列的話會先進行展平(flatten)再進行外積。
c = np.arange(5).reshape(1, 5)
d = np.random.randint(9, size=(5))
e = np.arange(6).reshape(1, 6)

#外積-一維陣列
np.outer(c, d)

print('c = ', c,
      '\nd =', d,
      '\nnp.outer(c, d) = \n', np.outer(c, d))

#外積-一維陣列
np.outer(e, d)

print('e = ', e,
      '\nd =', d,
      '\nnp.outer(e, d) = \n', np.outer(e, d))

c =  [[0 1 2 3 4]] 
d = [4 4 0 8 0] 
np.outer(c, d) = 
 [[ 0  0  0  0  0]
 [ 4  4  0  8  0]
 [ 8  8  0 16  0]
 [12 12  0 24  0]
 [16 16  0 32  0]]
e =  [[0 1 2 3 4 5]] 
d = [4 4 0 8 0] 
np.outer(e, d) = 
 [[ 0  0  0  0  0]
 [ 4  4  0  8  0]
 [ 8  8  0 16  0]
 [12 12  0 24  0]
 [16 16  0 32  0]
 [20 20  0 40  0]]


In [29]:
#外積-非一維陣列
#非一維陣列的話會先進行展平(flatten)再進行外積。

np.outer(a, b)

print('a = ', a,
      '\nb =', b,
      '\nnp.outer(a, b) = \n', np.outer(a, b))

a =  [[0 1 2]
 [3 4 5]] 
b = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
np.outer(a, b) = 
 [[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  2  4  6  8 10 12 14 16 18 20 22]
 [ 0  3  6  9 12 15 18 21 24 27 30 33]
 [ 0  4  8 12 16 20 24 28 32 36 40 44]
 [ 0  5 10 15 20 25 30 35 40 45 50 55]]


## 1.4 矩陣乘法：np.matmul() 與 @

- 如果2個都是二維陣列的話，matmul與 dot 相同。
- 在 matmul 中，多維的矩陣，將前 n-2 維視為後2维的元素後，進行乘法運算。
- matmul 不允許矩陣與純量相乘。

In [36]:
#矩陣乘法
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)
print('A = \n', A,
      '\nB = \n', B)
np.matmul(A, B)

A = 
 [[0 1 2]
 [3 4 5]] 
B = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [32]:
A @ B

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [37]:
#使用 matmul 進行矩陣與純量相乘時會產生錯誤。
np.matmul(A, 2)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

# 2. 矩陣操作

## 2.1 跡：numpy.trace()

In [73]:
A = np.arange(9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [74]:
np.trace(A)

12

## 2.2 行列式 (Determinant)：np.linalg.det()

$\vert A \vert= \begin{vmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{vmatrix}\\
= a_{11}\space a_{22}\space a_{33} + a_{12}\space a_{23}\space a_{31} + a_{13}\space a_{21}\space a_{32}
- a_{13}\space a_{22}\space a_{31} - a_{23}\space a_{32}\space a_{11} - a_{33}\space a_{12}\space a_{21}
$


圖解行列式運算 (Source: Wikipedia)
![](https://upload.wikimedia.org/wikipedia/commons/4/4d/Determinant-columns.png)


In [75]:
#矩陣為方陣
B = np.array([[3, 0, -1],[2, 4, 1],[7, 2, 3]])
np.linalg.det(B)

53.999999999999986

In [76]:
#矩陣非方陣
C = np.array([[3, 0],[4, 1],[7, 3]])
np.linalg.det(C)

LinAlgError: Last 2 dimensions of the array must be square

## 2.3 反矩陣：numpy.linalg.inv()

以三階矩陣為例：

$
A = \left[\begin{array}{ccc|ccc}
a_{11} & a_{12} & a_{13} & 1 & 0 & 0\\
a_{21} & a_{22} & a_{23} & 0 & 1 & 0\\
a_{31} & a_{32} & a_{33} & 0 & 0 & 1
\end{array}\right]
$

透過高斯約當法 (Gaussian Elimination)，可以得到右邊的矩陣即為 A 的反矩陣

$
A^{-1} = \left[\begin{array}{ccc|ccc}
1 & 0 & 0 & b_{11} & b_{12} & b_{13} \\
0 & 1 & 0 & b_{21} & b_{22} & b_{23}\\
0 & 0 & 1 & b_{31} & b_{32} & b_{33}
\end{array}\right]
$

呼叫 `inv()` 函式可以得到反矩陣。

In [87]:
#求矩陣B的反矩陣
B_rev = np.linalg.inv(B)
print(B_rev)

[[ 0.18518519 -0.03703704  0.07407407]
 [ 0.01851852  0.2962963  -0.09259259]
 [-0.44444444 -0.11111111  0.22222222]]


In [81]:
#若矩陣A不存在反矩陣，會出現錯誤
np.linalg.inv(A)

LinAlgError: Singular matrix

In [82]:
#將反矩陣乘上原矩陣
np.dot(B, B_rev)

array([[1.00000000e+00, 0.00000000e+00, 5.55111512e-17],
       [0.00000000e+00, 1.00000000e+00, 2.77555756e-17],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

## 2.4 轉置 (Transpose)：`np.transpose()`

$
A = \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}
$

$
A^T = \begin{bmatrix}
a_{11} & a_{21} & a_{31} \\
a_{12} & a_{22} & a_{23} \\
a_{13} & a_{23} & a_{33}
\end{bmatrix}
$


In [85]:
print('原矩陣 = \n', A,
      '\n轉置後矩陣 = \n', np.transpose(A))

原矩陣 = 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 
轉置後矩陣 = 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]


## 2.5 np.linalg.eig()：Numpy  矩陣操作 - 特徵值與特徵向量

- eig() 函式可以用來計算 __方陣__ 的特徵值(eigenvalue)與特徵向量(eigenvector)。
- eig() 回傳值有2個：eigenvalue與eigenvector。
- eigvals() 函式也可以計算特徵值

In [90]:
#矩陣為方陣
B = np.array([[-2, -4, 2],[-2, 1, 2],[4, 2, 5]])

#同時求特徵值(value)、特徵向量(vector)
val, vec = np.linalg.eig(B)
print('矩陣 B = \n',B,
      '\n特徵值 val = \n', val,   # eigenvalues
      '\n特徵向量 vec = \n', vec  # eigenvectors
     )

矩陣 B = 
 [[-2 -4  2]
 [-2  1  2]
 [ 4  2  5]] 
特徵值 val = 
 [-5.  3.  6.] 
特徵向量 vec = 
 [[ 0.81649658  0.53452248  0.05842062]
 [ 0.40824829 -0.80178373  0.35052374]
 [-0.40824829 -0.26726124  0.93472998]]


In [93]:
#用 eigvals() 函式計算特徵值
np.linalg.eigvals(B)

array([-5.,  3.,  6.])