# D06 使用 NumPy 存取各種檔案內容 - 作業

# 作業目標 

讀取存取陣列資料 


# 作業重點 

多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

## 題目: 

### 1. 將下兩列array存成npz檔 

array1 = np.array(range(30)) 

array2 = np.array([2,3,5]) 


### 2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

array3 = np.array([[4,5,6], [1,2,3]])


## 答案:
### 1. 將下兩列array存成npz檔
array1 = np.array(range(30))

array2 = np.array([2,3,5])

In [1]:
import numpy as np

#. 將下兩列array存成npz檔
a1 = np.array(range(30))
a2 = np.array([2,3,5])   
                  
with open('npzfile.npz', 'wb') as f:
    np.savez(f, array1=a1, array2=a2)


### 2. 讀取剛剛的npz檔，加入下列 array 一起存成新的npz檔

In [2]:
#讀取剛剛的npz檔
a1a2 = np.load('npzfile.npz')
print(a1a2.files)

#透過 file 屬性回傳list
a1a2.files    

['array1', 'array2']


['array1', 'array2']

In [16]:
#加入下列 array 一起存成新的npz檔
array3 = np.array([[4,5,6], [1,2,3]])

#將剛剛的檔案轉成字典
a1a2_dic = dict(a1a2)
#插入新增 array3
a1a2_dic["array3"] = np.array([[4,5,6], [1,2,3]])
a1a2_dic

#儲存為新的npz檔
np.savez('new.npz',**a1a2_dic)


array([[4, 5, 6],
       [1, 2, 3]])

In [6]:
#讀取新的 npz檔
new = np.load('new.npz')
new.files

['array1', 'array2', 'array3']

### 方法二

#### 1. 將下兩列array存成npz檔

In [7]:
#將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
np.savez('array.npz', array1, array2)

#### 2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

In [25]:
#讀取剛剛的npz檔
load_array = np.load('array.npz')

#加入下列array一起存成新的npz檔
array3 = np.array([[4,5,6],[1,2,3]])
np.savez('new_array.npz', load_array['arr_0'], load_array['arr_1'], array3)
ans = np.load('new_array.npz')

print(ans.files)
print('\n第一個array的內容：\n', ans['arr_0'], 
      '\n第二個array的內容：\n', ans['arr_1'],
      '\n第三個array的內容：\n', ans['arr_2'])

['arr_0', 'arr_1', 'arr_2']

第一個array的內容：
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 
第二個array的內容：
 [2 3 5] 
第三個array的內容：
 [[4 5 6]
 [1 2 3]]
